import { generateKeyPairSync, createVerify } from 'node:crypto'
import { expect, test } from 'vitest'
import {
  DEMO_EVENTS, DEMO_PATH, LP_PATH, buildGa4Requests, buildServiceAccountJwt, fetchClarity, fetchGa4, renderMarkdown, run, summarizeClarity, summarizeGa4,
} from './metrics-report.mjs'

const row = (dims, mets) => ({ dimensionValues: dims.map((v) => ({ value: v })), metricValues: mets.map((v) => ({ value: String(v) })) })

const landing = { rows: [row([LP_PATH], [25, 10, 24, 24, 42.5, 1.4, 6])] }
const funnel = { rows: [
  row([LP_PATH, LP_PATH], [25, 30]),
  row([LP_PATH, `${DEMO_PATH}`], [8, 9]),
  row([LP_PATH, `${DEMO_PATH}#/gacha/x`], [5, 7]),
] }
const events = { rows: [row(['demo_start'], [7, 7, 6]), row(['spin_first'], [4, 4, 4])] }

test('GA4 の要求: 期間・LP の絞り込み・デモのイベントの一覧', () => {
  const r = buildGa4Requests({ days: 7 })
  expect(r.landing.dateRanges[0]).toEqual({ startDate: '7daysAgo', endDate: 'yesterday' })
  expect(r.landing.dimensionFilter.filter.stringFilter.value).toBe(LP_PATH)
  expect(r.funnel.dimensions.map((d) => d.name)).toEqual(['landingPage', 'pagePath'])
  expect(r.events.dimensionFilter.filter.inListFilter.values).toEqual(DEMO_EVENTS)
})

test('GA4 の要約: しっかり見た割合・デモへの到達（複数ページは最大値で下限、合算で上限）', () => {
  const s = summarizeGa4({ landing, funnel, events })
  expect(s.sessions).toBe(25)
  expect(s.engaged).toBe(10)
  expect(s.engagedRate).toBe(40)
  expect(s.scrolledUsers).toBe(6)
  expect(s.scrolledRate).toBe(25)
  expect(s.avgDurationSec).toBe(43)
  expect(s.pagesPerSession).toBe(1.4)
  expect(s.toDemoSessions).toBe(8)
  expect(s.toDemoSessionsUpper).toBe(13)
  expect(s.toDemoRate).toBe(32)
  expect(s.pages[0]).toEqual({ path: LP_PATH, sessions: 25, views: 30 })
  expect(s.events.demo_start).toEqual({ count: 7, sessions: 7, users: 6 })
})

test('GA4 の要約: プロパティ全体と入口の一覧（LP が 0 のときの手がかり）', () => {
  const overview = { rows: [row(['/other/'], [12, 10]), row([LP_PATH], [3, 3])] }
  const total = { rows: [row([], [40, 33])] } // 次元なしの合計は上位 10 件の合計より大きい
  const s = summarizeGa4({ landing: {}, funnel: {}, events: {}, overview, total })
  expect(s.allSessions).toBe(40)
  expect(summarizeGa4({ landing: {}, funnel: {}, events: {}, overview }).allSessions).toBe(15)
  expect(s.topLanding[0]).toEqual({ path: '/other/', sessions: 12, users: 10 })
  const md = renderMarkdown({ days: 7, ga4: s, clarity: null })
  expect(md).toContain('プロパティ全体のセッション（同じ期間）: **40**')
  expect(md).toContain('| `/other/` | 12 | 10 |')
  const zero = renderMarkdown({ days: 7, ga4: summarizeGa4({ landing: {}, funnel: {}, events: {}, overview: {} }), clarity: null })
  expect(zero).toContain('GA4_PROPERTY_ID')
})

test('GA4 の要約: 行が無いときは 0 と割合なし', () => {
  const s = summarizeGa4({ landing: {}, funnel: {}, events: {} })
  expect(s.sessions).toBe(0)
  expect(s.engagedRate).toBeNull()
  expect(s.toDemoRate).toBeNull()
  expect(s.events).toEqual({})
})

const clarityPayload = [
  { metricName: 'Traffic', information: [
    { URL: 'https://doc-gif.github.io/lastpiece-lp/', totalSessionCount: '25', totalBotSessionCount: '12', distinctUserCount: '24', pagesPerSessionPercentage: '1.4' },
    { URL: 'https://doc-gif.github.io/jtcc-group-e/', totalSessionCount: '9', totalBotSessionCount: '1', distinctUserCount: '8', pagesPerSessionPercentage: '3.2' },
  ] },
  { metricName: 'ScrollDepth', information: [{ URL: 'https://doc-gif.github.io/lastpiece-lp/', averageScrollDepth: '28.69' }] },
  { metricName: 'EngagementTime', information: [{ URL: 'https://doc-gif.github.io/lastpiece-lp/', totalTime: '900', activeTime: '400' }] },
  { metricName: 'DeadClickCount', information: [{ URL: 'https://doc-gif.github.io/lastpiece-lp/', sessionsWithMetricPercentage: '8', sessionsCount: '2' }] },
  { metricName: 'RageClickCount', information: [{ URL: 'https://doc-gif.github.io/lastpiece-lp/', sessionsWithMetricPercentage: '0' }] },
]

test('Clarity の要約: URL で LP とデモに分ける', () => {
  const c = summarizeClarity(clarityPayload)
  expect(c.lp).toMatchObject({ sessions: 25, botSessions: 12, users: 24, pagesPerSession: 1.4, averageScrollDepth: 28.7, activeTimeSec: 400, deadClickRate: 8, rageClickRate: 0 })
  expect(c.demo).toMatchObject({ sessions: 9, botSessions: 1, users: 8, pagesPerSession: 3.2, averageScrollDepth: null, deadClickRate: null })
})

test('Clarity の要約: 空でも落ちない', () => {
  expect(summarizeClarity({ metrics: [] }).lp.sessions).toBe(0)
  expect(summarizeClarity(null).demo.users).toBe(0)
})

test('Markdown: 到達率と未設定の表示、秘密は出さない', () => {
  const md = renderMarkdown({ days: 7, ga4: summarizeGa4({ landing, funnel, events }), clarity: null, errors: ['Clarity: 401'] }, new Date('2026-09-26T10:00:00Z'))
  expect(md).toContain('**8（32%）**')
  expect(md).toContain('最大 13')
  expect(md).toContain('| demo_start | 7 | 7 | 6 |')
  expect(md).toContain('Clarity: 未設定')
  expect(md).toContain('- Clarity: 401')
  expect(md).toContain('_Generated by [Claude Code]')
  const empty = renderMarkdown({ days: 7, ga4: summarizeGa4({ landing: {}, funnel: {}, events: {} }), clarity: summarizeClarity(clarityPayload) })
  expect(empty).toContain('まだ届いていない')
  expect(empty).toContain('| セッション（ボット除外数） | 25（12） | 9（1） |')
})

test('サービスアカウントの JWT: RS256 で署名され、iss・scope・exp が入る', () => {
  const { privateKey, publicKey } = generateKeyPairSync('rsa', { modulusLength: 2048 })
  const pem = privateKey.export({ type: 'pkcs8', format: 'pem' })
  const jwt = buildServiceAccountJwt({ client_email: 'sa@example.iam.gserviceaccount.com', private_key: pem }, { now: 1_000_000 })
  const [h, c, sig] = jwt.split('.')
  const dec = (s) => JSON.parse(Buffer.from(s.replace(/-/g, '+').replace(/_/g, '/'), 'base64').toString())
  expect(dec(h)).toEqual({ alg: 'RS256', typ: 'JWT' })
  expect(dec(c)).toMatchObject({ iss: 'sa@example.iam.gserviceaccount.com', aud: 'https://oauth2.googleapis.com/token', iat: 1_000_000, exp: 1_003_600 })
  expect(dec(c).scope).toContain('analytics.readonly')
  const v = createVerify('RSA-SHA256'); v.update(`${h}.${c}`)
  expect(v.verify(publicKey, Buffer.from(sig.replace(/-/g, '+').replace(/_/g, '/'), 'base64'))).toBe(true)
  expect(() => buildServiceAccountJwt({})).toThrow(/client_email/)
})

const fakeFetch = (routes) => async (url, init = {}) => {
  for (const [match, handler] of routes) if (String(url).includes(match)) return handler(url, init)
  return { ok: false, status: 404, text: async () => 'no route', json: async () => ({}) }
}
const okJson = (body) => ({ ok: true, status: 200, json: async () => body, text: async () => JSON.stringify(body) })

test('GA4 の取得: トークン → 3 つの runReport を property に送る', async () => {
  const { privateKey } = generateKeyPairSync('rsa', { modulusLength: 2048 })
  const sa = { client_email: 'sa@x', private_key: privateKey.export({ type: 'pkcs8', format: 'pem' }) }
  const calls = []
  const f = fakeFetch([
    ['oauth2.googleapis.com/token', (u, i) => { calls.push(['token', i.body.get('grant_type')]); return okJson({ access_token: 'tok' }) }],
    [':runReport', (u, i) => { const b = JSON.parse(i.body); calls.push(['report', String(u), i.headers.authorization, (b.dimensions ?? []).map((d) => d.name).join('+')]); return okJson(!b.dimensions ? { rows: [] } : b.dimensions[0].name === 'eventName' ? events : b.dimensions.length === 2 ? funnel : b.orderBys ? { rows: [] } : landing) }],
  ])
  const s = await fetchGa4({ propertyId: '123456', saKey: JSON.stringify(sa), days: 7, fetchImpl: f })
  expect(calls[0]).toEqual(['token', 'urn:ietf:params:oauth:grant-type:jwt-bearer'])
  expect(calls.filter((c) => c[0] === 'report')).toHaveLength(5)
  expect(calls[1][1]).toContain('/properties/123456:runReport')
  expect(calls[1][2]).toBe('Bearer tok')
  expect(s.toDemoSessions).toBe(8)
})

test('Clarity の取得: Bearer と numOfDays=3、失敗は例外', async () => {
  const f = fakeFetch([['clarity.ms/export-data', (u, i) => { expect(String(u)).toContain('numOfDays=3'); expect(i.headers.authorization).toBe('Bearer ct'); return okJson(clarityPayload) }]])
  const c = await fetchClarity({ token: 'ct', fetchImpl: f })
  expect(c.lp.sessions).toBe(25)
  await expect(fetchClarity({ token: 'ct', fetchImpl: fakeFetch([['clarity.ms', () => ({ ok: false, status: 401, text: async () => 'bad token' })]]) })).rejects.toThrow(/401/)
})

test('run: 秘密が無い取得元は飛ばし、あるものの失敗はエラー欄に出る', async () => {
  const out = []
  const r = await run({ env: { CLARITY_TOKEN: 'ct' }, args: ['--days', '3'], fetchImpl: fakeFetch([['clarity.ms', () => ({ ok: false, status: 500, text: async () => 'boom' })]]), log: (m) => out.push(m) })
  expect(r.ga4).toBeNull()
  expect(r.clarity).toBeNull()
  expect(r.errors[0]).toMatch(/Clarity: .*500/)
  expect(out[0]).toContain('GA4: 未設定')
  expect(out[0]).not.toContain('ct')
})

test('CLI: 秘密が無ければ正常終了（0）、設定済みの取得元が失敗したら 2', async () => {
  const { spawnSync } = await import('node:child_process')
  const ok = spawnSync(process.execPath, ['scripts/metrics-report.mjs', '--days', '3'], { env: { PATH: process.env.PATH }, encoding: 'utf8' })
  expect(ok.status).toBe(0)
  expect(ok.stdout).toContain('GA4: 未設定')
  const bad = spawnSync(process.execPath, ['scripts/metrics-report.mjs'], { env: { PATH: process.env.PATH, CLARITY_TOKEN: 'x', HTTPS_PROXY: 'http://127.0.0.1:9', https_proxy: 'http://127.0.0.1:9' }, encoding: 'utf8', timeout: 20000 })
  expect(bad.status).toBe(2)
  expect(bad.stdout).toContain('取得できなかったもの')
})
